Pass error codes on close to Amplify
aws-amplify/amplify-ui-android pull request #106
Opened 2023-12-14 23:17 UTC by tjleing

- [ ] PR conforms to [Pull Request](https://github.com/aws-amplify/amplify-ui-android/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guidelines.

*Issue #, if available:*

*Description of changes:*

*How did you test these changes?*
(Please add a line here how the changes were tested)

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

*General Checklist*
- [ ] Added Unit Tests
- [ ] Added Integration Tests
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-22 20:54 UTC, tylerjroach requested changes

2023-12-22 20:54 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/util/ErrorCode.kt
> +enum class ErrorCode(val code: Int) {
Needs to be internal

2023-12-22 20:54 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/util/ErrorCode.kt
> +    SUCCESS(1000),
Lets leave out concept of success.

2023-12-22 20:54 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessCoordinator.kt
> +        val code = if (disconnectEventReceived) ErrorCode.SUCCESS else ErrorCode.DISPOSED
This may be the wrong place to use Disposed. The real sign of a dispose is `onDispose` on ChallengeView.

2023-12-22 20:54 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/camera/LivenessCoordinator.kt
> +        val code = if (disconnectEventReceived) ErrorCode.SUCCESS else ErrorCode.DISPOSED
We shouldn't send success

2023-12-22 20:54 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/model/FaceLivenessDetectionException.kt
> +    val errorCode: ErrorCode,
ErrorCode feels unnecessary to be part of the exception. We can easily infer the Error by Exception type. Ex:

2023-12-22 20:54 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/model/FaceLivenessDetectionException.kt
>      class SessionTimedOutException(
I don't think this timeout is what you think it is. This is if server provides a timeout (I think) and not that a user failed to match oval in given number of seconds. We should be sending error on face match timeout, which comes from us, not the server.

2023-12-26 16:12 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/util/ErrorCode.kt
> +enum class ErrorCode(val code: Int) {
pushed changes

2023-12-26 16:12 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/util/ErrorCode.kt
> +    SUCCESS(1000),
pushed changes

2023-12-26 16:12 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/model/FaceLivenessDetectionException.kt
> +    val errorCode: ErrorCode,
pushed changes.

2023-12-26 16:13 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/model/FaceLivenessDetectionException.kt
>      class SessionTimedOutException(
SessionTimedOutException no longer has TIMEOUT error code.

2023-12-26 19:15 UTC, sktimalsina submitted a review, later dismissed

2023-12-26 19:22 UTC, ankpshah approved these changes

2023-12-26 19:41 UTC, sktimalsina approved these changes

2023-12-26 19:50 UTC, ankpshah approved these changes

2023-12-26 20:18 UTC, merged