feat(authenticator): Add support for Email MFA
aws-amplify/amplify-ui-android pull request #199
Opened 2024-10-07 22:26 UTC by vincetran

- [x] PR conforms to [Pull Request](https://github.com/aws-amplify/amplify-ui-android/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guidelines.

*Issue #, if available:* N/A

*Description of changes:*
The PR aims to add support for Email MFA that has been released by Cognito.
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-advanced-security-email-mfa.html

The PR for the Amplify-Android change can be found here: https://github.com/aws-amplify/amplify-android/pull/2935

This PR will be in draft mode until the above change has been released so that this PR can ingest the new version.

*How did you test these changes?*
Manual testing, new and updated tests pass

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

*General Checklist*
- [x] Added Unit Tests
- [x] Added Integration Tests
- [x] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)
- [x] Ensure commit message has the appropriate scope (e.g `fix(liveness): message`, `fix(authenticator): message`, `fix(all): message`)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-25 16:43 UTC, vincetran commented on gradle/libs.versions.toml
> +kotlin = "1.9.10"
This change was required due to the the AWS SDK upgrade

2024-10-28 20:44 UTC, tylerjroach commented on authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/SignInContinueWithEmailSetupTest.kt
> +    fun `Submit button label is Submit`() {
Should this be continue?

2024-10-29 15:09 UTC, tylerjroach requested changes

2024-10-29 15:09 UTC, tylerjroach commented on authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/SignInConfirmCustom.kt
> +        AuthenticatorTitle(stringResource(R.string.amplify_ui_authenticator_title_signin_confirm_custom_challenge))
This seems like a somewhat breaking change.

2024-10-29 15:09 UTC, tylerjroach commented on authenticator/src/main/res/values/titles.xml
> +    <string name="amplify_ui_authenticator_title_signin_confirm_custom_challenge">Enter your sign in code</string>
Need to discuss how this is a semi-breaking change and how to avoid.

2024-10-29 15:09 UTC, tylerjroach commented on authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/SignInContinueWithEmailSetupTest.kt
> +    fun `title is Setup Two-Factor Auth Method`() {
Wrong title is being shown. This test should be failing?

2024-10-29 17:21 UTC, tylerjroach commented on authenticator/src/main/res/values/titles.xml
> +    <string name="amplify_ui_authenticator_title_signin_confirm_custom_challenge">Enter your sign in code</string>
After product discussion, we shouldn't have added this. Continue using previous string which now reads as "Verify your sign-in". That shouldn't impact custom flow as "Enter your sign in code" and "Verify your sign-in" are equivalent.

2024-10-29 17:25 UTC, tylerjroach commented on authenticator/src/main/res/values/titles.xml
> +    <string name="amplify_ui_authenticator_title_signin_confirm_custom_challenge">Enter your sign in code</string>
@harsh62 Lets revert swift back if you added a new string here.

2024-10-29 17:27 UTC, tylerjroach commented on authenticator/src/main/res/values/titles.xml
> +    <string name="amplify_ui_authenticator_title_signin_confirm_custom_challenge">Enter your sign in code</string>
Actually, it appears swift already has its own dedicated string for custom where Android doesn't. For consistency, unless you are opposed, it would be best to update custom string to match MFA so Android and Swift match.

2024-10-29 18:34 UTC, tylerjroach commented on authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/SignInContinueWithEmailSetupTest.kt
> +    fun `Submit button label is Submit`() {
test was failing as expected. fixing.

2024-10-29 18:34 UTC, tylerjroach commented on authenticator/src/main/java/com/amplifyframework/ui/authenticator/ui/SignInConfirmCustom.kt
> +        AuthenticatorTitle(stringResource(R.string.amplify_ui_authenticator_title_signin_confirm_custom_challenge))
Removing string

2024-10-29 18:35 UTC, tylerjroach commented on authenticator/src/test/java/com/amplifyframework/ui/authenticator/ui/SignInContinueWithEmailSetupTest.kt
> +    fun `title is Setup Two-Factor Auth Method`() {
test was failing as expected. fixing

2024-10-30 13:09 UTC, tylerjroach approved these changes

2024-10-30 16:32 UTC, vincetran reviewed
Your changes look good, @tylerjroach. I can't give an explicit approval because it's my PR.

2024-10-30 16:48 UTC, mattcreaser submitted a review, later dismissed

2024-10-31 16:46 UTC, mattcreaser approved these changes

2024-10-31 16:46 UTC, merged