fix(liveness): use updated Liveness oval algorithm
aws-amplify/amplify-ui-android pull request #95
Opened 2023-11-16 02:22 UTC by tjleing

- [x] PR conforms to [Pull Request](https://github.com/aws-amplify/amplify-ui-android/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guidelines.

*Description of changes:*
use blazeface-reported ear positions to better calculate oval.  right now, works well at longer distances but messes up at short range (top is calculated incorrectly it seems?  shouldn't be negative).

*How did you test these changes?*
(Please add a line here how the changes were tested)

*Documentation update required?*
- [x] No
- [ ] Yes (Please include a PR link for the documentation update)

*General Checklist*
- [ ] Added Unit Tests
- [ ] Added Integration Tests
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-29 14:32 UTC, tylerjroach commented
I'm not sure what you were trying to do with the visibility annotation changes but they were unncecessary and actually brought internal code to be marked as public. I went ahead and pushed changes to revert all of those annotations.

Pushed a few other minor cleanups. Please take a look at my changes to confirm nothing unexpected was changed.

2023-11-29 14:33 UTC, tylerjroach approved these changes

2023-11-29 14:37 UTC, tylerjroach requested changes

2023-11-29 14:37 UTC, tylerjroach commented on liveness/src/test/java/com/amplifyframework/ui/liveness/ml/FaceDetectorTest.kt
> +        ).isEmpty
Is this meant to be an assertion?

2023-11-29 14:56 UTC, tylerjroach commented on liveness/src/test/java/com/amplifyframework/ui/liveness/ml/FaceDetectorTest.kt
> +        ).isEmpty
This is no longer relevant. I went ahead and fixed the test. Please confirm it looks as expected.

2023-11-29 17:42 UTC, tylerjroach approved these changes

2023-11-29 18:18 UTC, ankpshah commented on liveness/src/main/java/com/amplifyframework/ui/liveness/ml/FaceDetector.kt
> +        private const val GOLDEN_RATIO = 1.68f
Golden Ratio should be 1.618

2023-11-29 20:01 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/ml/FaceDetector.kt
> +        private const val GOLDEN_RATIO = 1.68f
awaiting confirmation from science. This change was intentional by directions given, but the value could have been incorrect in the one provided to us.

2023-11-29 20:35 UTC, tylerjroach approved these changes

2023-11-29 20:36 UTC, tylerjroach commented on liveness/src/main/java/com/amplifyframework/ui/liveness/ml/FaceDetector.kt
> +        private const val GOLDEN_RATIO = 1.68f
reverted

2023-11-30 17:36 UTC, tylerjroach approved these changes

2023-11-30 19:03 UTC, ankpshah approved these changes

2023-11-30 21:08 UTC, merged